### ISSUE TITLE
make deploy to heroku button & aliexpress affiliate automation

### ISSUE THREAD

**Issue by branchmaster** [crox-safe/AmazonBot#1]
Hi CrOx,
please make deploy to heroku button for easy deployable & if it's possible integrate aliexpress affiliate automation too.
waiting for your response
finest regards

**Comment by crox-safe** [comment]
sure, I will be implementing heroku.

about aliexpress i could also implement it, but do you have any idea for a new name for the repository?

cheers

**Comment by branchmaster** [comment]
yeah , I'm offering aliazon for both amazon & aliexpress automation affiliate bot.
waiting for your commits :)
finest regards

**Comment by crox-safe** [comment]
i will keep it in mind, commits are welcome!
