### ISSUE TITLE
Come si setta?

### ISSUE THREAD

**Issue by DotHack88** [crox-safe/AmazonBot#7]
Ciao potresti essere cosi gentile da potermi spiegare da dove posso attingere a queste informazioni?

  "amazon": {
  "KEY": "KEY_AMAZON",
  "SECRET": "SECRET_KEY_AMAZON",
  "TAG": "TAG_AMAZON",
  "COUNTRY": "COUNTRY"}

**Comment by crox-safe** [comment]
For this you will need to be affiliated to Amazon Product Advertising API

You can see more about it [here](https://webservices.amazon.com/paapi5/documentation/register-for-pa-api.html)
